apiVersion: apps/v1
kind: Deployment
metadata:
  name: sagini-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sagini
  template:
    metadata:
      labels:
        app: sagini
    spec:
      containers:
      - name: sagini
        image: 622339756908.dkr.ecr.us-east-1.amazonaws.com/sagini:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-service
spec:
  selector:
    app: myjavaapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer

